
- name: Application user Creation
  ansible.builtin.import_role:
    name: common
    tasks_from: roboshop_user.yaml


- name: Java Setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java_maven.yaml


- name: install mysql python libraries
  ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
  loop:
    - cryptography
    - PyMySQL

- name: import shipping data into mysql
  community.mysql.mysql_db:
      state: import
      name: all
      login_host: sql.sureshdevops.fun
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql


- name: Service creation and starting service
  ansible.builtin.import_role:
    name: common
    tasks_from: system.yaml