- name: Cart Setup
  hosts: cart
  become: yes

  tasks: 
  - name: enabling & disabling version
    ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:20 -y

  - name: installing the nodejs 
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Creating Application user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      home: /app
      shell: /sbin/nologin
      system: yes

  - name: Remove App Directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create App Directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete cart file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: download cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip   

  - name: Unzip the cart files
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    community.general.npm:
      path: /app
  
  - name: Copying the service file to systemd
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: daemon reload enable and start
    ansible.builtin.shell: systemctl daemon-reload
  
  - name: Enabling and starting service
    ansible.builtin.service:
      name: cart
      state: restarted


  