- name: install maven and MYSQL client
  ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
  loop:
    - maven
    - mysql

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
      chdir: /app

- name: move jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
      chdir: /app


