- name: Copying the {{ component }} service file to systemd
  ansible.builtin.copy:
    src: "{{ component }}.service.j2"
    dest: /etc/sysetmd/system/{{ component }}.service
  notify: daemon reload

- name: start the service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes  